var dummybase = [
'Today its up to you to create the peacefulness you long for.',
'A friend asks only for your time not your money.',
'If you refuse to accept anything but the best, you very often get it.',
'A smile is your passport into the hearts of others.',
'Your high-minded principles spell success.',
'Hard work pays off in the future, laziness pays off now.',
'Change can hurt, but it leads a path to something better.',
'Enjoy the good luck a companion brings you.',
'People are naturally attracted to you.',
'A chance meeting opens new doors to success and friendship.',
'If you have something good in your life, dont let it go!',
'What ever youre goal is in life, embrace it visualize it, and for it will be yours.',
'You cannot love life until you live the life you love.',
'Be on the lookout for coming events; They cast their shadows beforehand.',
'Land is always on the mind of a flying bird.',
'Meeting adversity well is the source of your strength.',
'A dream you have will come true.',
'Our deeds determine us, as much as we determine our deeds.',
'Never give up. Youre not a failure if you dont give up.',
'There is no greater pleasure than seeing your loved ones prosper.',
'You already know the answer to the questions lingering inside your head.',
'It is now, and in this world, that we must live.',
'You must try, or hate yourself for not trying.',
'You can make your own happiness.',
'The greatest risk is not taking one.',
'Love can last a lifetime, if you want it to.',
'Adversity is the parent of virtue.',
'Serious trouble will bypass you.',
'Now is the time to try something new.',
'If you feel you are right, stand firmly by your convictions.',
'If winter comes, can spring be far behind?',
'Keep your eye out for someone special.',
'You are very talented in many ways.',
'A stranger, is a friend you have not spoken to yet.',
'A new voyage will fill your life with untold memories.',
'You will travel to many exotic places in your lifetime.',
'Your ability for accomplishment will follow with success.',
'Nothing astonishes men so much as common sense and plain dealing.',
'Its amazing how much good you can do if you dont care who gets the credit.'
];

exports.dummybase = dummybase;